app/SNS_APPLICATION/flaskr/views.py
from datetime import datetime

from flask import (
    Blueprint, abort, request, render_template,
    redirect, url_for, flash, session
)
from flask_login import (
    login_user, login_required, logout_user, current_user
)
from flaskr.models import (
    User, PasswordResetToken, UserConnect
)
from flaskr import db

from flaskr.forms import (
    LoginForm, RegisterForm, ResetPasswordForm, ForgotPasswordForm, 
    UserForm, ChangePasswordForm, UserSearchForm, ConnectForm
)


bp = Blueprint('app', __name__, url_prefix='')

@bp.route('/')
def home():
    return render_template('home.html')

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('app.home'))

@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_email(form.email.data)
        if user and user.is_active and user.validate_password(form.password.data):
            login_user(user, remember=True)
            next = redirect.args.get('next')
            if not next:
                next = url_for('app.home')
            return redirect(next)
        elif not user:
            flash('存在しないユーザーです')
        elif not user.is_active:
            flash('無効なユーザーです。パスワードを再設定してください')
        elif not user.validate_password(form.password.data):
            flash('メールアドレスとパスワードの組み合わせが誤っています')
    return render_template('login.html', form=form)

@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User(
            username = form.username.data,
            email = form.email.data
        )
        with db.session.begin(subtransactions=True):
            user.create_new_user()
        db.session.commit()
        token = ''
        with db.session.begin(subtransactions=True):
            token = PasswordResetToken.publish_token(user)
        db.session.commit()
        # メールに飛ばしたり
        print(f'パスワード設定用URL: http://127.0.0.1:5001/reset_password/{token}')
        flash('パスワード設定用のURLをお送りしました。ご確認ください')
        return redirect(url_for('app.login'))
    return render_template('register.html', form=form)

@bp.route('/reset_password/<uuid:token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm(request.form)
    reset_user_id = PasswordResetToken.get_user_id_by_token(token)
    if not reset_user_id:
        abort(500)
    if request.method=='POST' and form.validate():
        password = form.password.data
        user = User.select_user_by_id(reset_user_id)
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
            PasswordResetToken.delete_token(token)
        db.session.commit()
        flash('パスワードを更新しました。')
        return redirect(url_for('app.login'))
    return render_template('reset_password.html', form=form)

@bp.route('/forgot_password', methods=['GET','POST'])
def forgot_password():
        form = ForgotPasswordForm(request.form)
        if request.method == 'POST' and form.validate():
            email = form.email.data
            user = User.select_user_by_email(email)
            if user:
                with db.session.begin(subtransactions=True):
                    token = PasswordResetToken.publish_token(user)
                db.session.commit()
                reset_url = f'http://127.0.0.1:5001/reset_password/{token}'
                print(reset_url)
                flash('パスワード再登録用のURLを発行しました')
            else:
                flash('存在しないユーザーです')
        return render_template('forgot_password.html', form=form)

@bp.route('/user', methods=['GET', 'POST'])
@login_required
def user():
    form = UserForm(request.form)
    if request.method == 'POST' and form.validate():
        user_id = current_user.get_id()
        user = User.select_user_by_id(user_id)
        with db.session.begin(subtransactions=True):
            user.username = form.username.data
            user.email = form.email.data
            file = request.files[form.picture_path.name].read()
            if file:
                file_name = user_id + '_' + str(int(datetime.now().timestamp())) + '.jpg'
                picture_path = 'flaskr/static/user_image/' + file_name
                open(picture_path, 'wb').write(file)
                user.picture_path = 'user_image/' + file_name
        db.session.commit()
        flash('ユーザー情報の更新に成功しました')
    return render_template('user.html', form=form)

@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        user = User.select_user_by_id(current_user.get_id())
        password = form.password.data
        with db.session.begin(subtransactions=True):
            user.save_new_password(password)
        db.session.commit()
        flash('パスワードの更新に成功しました')
        return redirect(url_for('app.user'))
    return render_template('change_password.html', form=form)

@bp.route('/user_search', methods=['GET', 'POST'])
@login_required
def user_search():
    form = UserSearchForm(request.form)
    connect_form = ConnectForm()
    session['url'] = 'app.user_search'
    users = None
    if request.method == 'POST' and form.validate():
        username = form.username.data
        users = User.search_by_name(username)
    return render_template('user_search.html', form=form, connect_form=connect_form, users=users)

@bp.route('/connect_user', methods=['POST'])
@login_required
def connect_user():
    form = ConnectForm(request.form)
    if request.method == 'POST' and form.validate():
        if form.connect_condition.data == 'connect':
            new_connect = UserConnect(current_user.get_id(), form.to_user_id.data)
            with db.session.begin(subtransactions=True):
                new_connect.create_new_connect()
            db.session.commit()
        elif form.connect_condition.data == 'accept':
            connect = UserConnect.select_by_from_user_id(form.to_user_id.data)
            if connect:
                with db.session.begin(subtransactions=True):
                    connect.update_status()
                db.session.commit()
    next_url = session.pop('url', 'app:home')
    return redirect(url_for(next_url))

@bp.app_errorhandler(404)
def page_not_found(e):
    return redirect(url_for('app.home'))

@bp.app_errorhandler(500)
def server_error(e):
    return render_template('500.html'), 500

app/SNS_APPLICATION/flaskr/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
    <dd>
        {{ field(**kwargs) | safe }}
        {% if field.errors %}
        <ul class="errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </dd>
</dt>
{% endmacro %}

app/SNS_APPLICATION/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Flask SNS{% endblock %}</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg nvabar-light bg-light">
            <a class="navbar-brand" href="{{url_for('app.home')}}">Home</a>
            {% if current_user.is_authenticated %}
            <a class="navbar-brand" href="{{url_for('app.logout')}}">ログアウト</a>
            <a class="navbar-brand" href="{{url_for('app.user')}}">ユーザー情報編集</a>
            <a class="navbar-brand" href="{{url_for('app.user_search')}}">ユーザ検索</a>
            {% else %}
            <a class="navbar-brand" href="{{url_for('app.login')}}">ログイン</a>
            <a class="navbar-brand" href="{{url_for('app.register')}}">登録</a>
            {% endif %}
        </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

app/SNS_APPLICATION/flaskr/templates/change_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

app/SNS_APPLICATION/flaskr/templates/forgot_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード再発行 - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<h1>パスワード再発行画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% end block %}

app/SNS_APPLICATION/flaskr/templates/home.html
{% extends "base.html" %}
{% block title %}
Home - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
    {% if current_user.is_authenticated %}
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
            <img class="user-image-big" src="{{ url_for('static', filename=current_user.picture_path) }}">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <p>ユーザー名: {{ current_user.username }}</p>
        <p>メールアドレス: {{ current_user.email }}</p>
    </div>
    {% else %}
        <p>ログイン or 登録をしてください</p>
    {% endif %}
    </div>
</div>
{% end block %}

app/SNS_APPLICATION/flaskr/templates/login.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
LOG IN - {{ super() }}
{% endblock %}
{% block content %}
{% for message in get_flashed_messages() %}
{{ message }}
{% endfor %}
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
    <a href="{{url_for('app.forgot_password')}}">
        パスワードを忘れた場合
    </a>
</div>
{% end block %}

app/SNS_APPLICATION/flaskr/templates/register.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>ユーザ情報登録が面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ form.submit() }}
    </form>
</div>
{% end block %}

app/SNS_APPLICATION/flaskr/templates/reset_password.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1>ユーザ情報登録画面</h1>
<div class="row">
    <form method="POST">
        {{ form.csrf_token }}
        {{ render_field(form.password) }}
        {{ render_field(form.confirm_password) }}
        {{ form.submit() }}
    </form>
</div>
{% endblock %}

app/SNS_APPLICATION/flaskr/templates/user.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー情報編集画面 - {{ super() }}
{% endblock %}
{% block content %}

<div class="row">
    <div class="col-lg-8 offset-lg-4" >
        {% for message in get_flashed_messages() %}
        {{ message }}
        {% endfor %}
    </div>
    <div class="col-lg-2 offset-lg-2">
        {% if current_user.picture_path %}
        <img class="user-image-big" src="{{url_for('static', filename=current_user.picture_path)}}" alt="">
        {% endif %}
    </div>
    <div class="col-lg-4 offset-lg-2">
        <form method="POST" enctype="multipart/form-data">
            {{form.csrf_token}}
            {{render_field(form.username, value=current_user.username)}}
            {{render_field(form.email, value=current_user.email)}}
            {{render_field(form.picture_path)}}
            {{form.submit()}}
        </form>
        <a href="{{url_for('app.change_password')}}">パスワードを変更する</a>
    </div>
</div>
{% end block %}

app/SNS_APPLICATION/flaskr/templates/user_search.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザ検索 - {{ super() }}
{% endblock %}
{% block content %}
<div class="jumbotron">
    <p>ユーザ検索画面</p>
</div>
<div class="row">
    <div class="col-lg-12">
        <form method="POST">
            {{ form.csrf_token }}
            {{ render_field(form.username) }}
            {{ form.submit() }}
        </form>
    </div>
    <div class="col-lg-12">
        {% if users %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ユーザ画像</th>
                    <th>ユーザ名</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users%}
                <tr>
                    <th>{{ loop.index }}</th>
                    {% if user.picture_path %}
                    <th>
                        <img class="user-image-small" src="{{url_for('static', filename=user.picture_path)}}" alt="">
                    </th>
                    {% else %}
                    <th></th>
                    {% endif %}
                    <th>{{ user.username }}</th>
                    <th>
                        {% if user.joined_status_from_to == 2 or user.joined_status_to_from == 2 %}
                        友達
                        {% elif user.joined_status_from_to == 1%}
                        友達申請中
                        {% elif user.joined_status_from_to == 1%}
                        <form method="POST" action="{{ url_for('app.connect_user')}}">
                            {{ connect_form.csrf_token }}
                            {{ connect_form.connect_condition(value='accept') }}
                            {{ connect_form.to_user_id(value=user.id) }}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請を承認する')}}
                        </form>
                        {% else %}
                        <form method="POST" action="{{ url_for('app.connect_user') }}">
                            {{ connect_form.csrf_token }}
                            {{ connect_form.connect_condition(value='connect') }}
                            {{ connect_form.to_user_id(value=user.id) }}
                            {{ connect_form.submit(class='btn btn-primary', value='友達申請する')}}
                        </form>
                        {% endif %}
                    </th>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}